layout_spectrum: 0.8694378163199872
typography_spectrum: 0.9191029700450599
color:
  brandStrength: 0.5743260136805475
  lightness: 0.3427379431668669
  saturation: 0.5377400629222393
  rhythmicContrast: 0.45607483363710344
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: WHATÂ´S COOKING
